USE ECOMMERCE.DEV


WITH stg_ecommerce AS ( SELECT * FROM ECOMMERCE_RAW )


SELECT 
ID AS ID_ROW,
WAREHOUSE_BLOCK,
MODE_OF_SHIPMENT,
CUSTOMER_CARE_CALLS,
CUSTOMER_RATING,
COST_OF_THE_PRODUCT AS COST_PRODUCT,
PRIOR_PURCHASES,
INITCAP ( PRODUCT_IMPORTANCE ) AS PRODUCT_IMPORTANCE,
GENDER,
DISCOUNT_OFFERED,
WEIGHT_IN_GMS
FROM stg_ecommerce

-- Derive DIM Stock

WITH DIM_WAREHOUSE AS(

SELECT 
    WAREHOUSE_BLOCK AS WAREHOUSE_BLOCK_ID,
    CASE WHEN WAREHOUSE_BLOCK = 'A' THEN 'Alvada'
    WHEN WAREHOUSE_BLOCK = 'B' THEN 'Balvada'
    WHEN WAREHOUSE_BLOCK = 'C' THEN 'Calvada'
    WHEN WAREHOUSE_BLOCK = 'D' THEN 'Dpires'
    WHEN WAREHOUSE_BLOCK = 'F' THEN 'Falvada'
    ELSE 'N/A' END AS DESCRIPTION_WAREHOUSE
    FROM ECOMMERCE.DEV.STG_ECOMMERCE
    
)

SELECT DISTINCT 
WAREHOUSE_BLOCK_ID,
DESCRIPTION_WAREHOUSE
FROM DIM_WAREHOUSE
ORDER BY WAREHOUSE_BLOCK_ID ASC





-- Derive DIM Mode Of Shipment

WITH DIM_MODE_SHIPMENT AS(

SELECT 
    MODE_OF_SHIPMENT AS MODE_OF_SHIPMENT_ID,
    CASE WHEN MODE_OF_SHIPMENT = 'Flight' THEN 'Azul'
    WHEN MODE_OF_SHIPMENT = 'Ship' THEN 'Titanic'
    WHEN MODE_OF_SHIPMENT = 'Road' THEN 'Optimus Prime'
    ELSE 'N/A' END AS IN_CHARGE_OF
    FROM ECOMMERCE.DEV.STG_ECOMMERCE
    
)

SELECT DISTINCT 
MODE_OF_SHIPMENT_ID,
IN_CHARGE_OF
FROM DIM_MODE_SHIPMENT



-- Derive DIM_GENDER

WITH DIM_GENDER AS(

SELECT 
    GENDER AS GENDER_ID,
    CASE WHEN GENDER = 'M' THEN 'Male'
    WHEN GENDER = 'F' THEN 'Female'
    ELSE 'Other' END AS DESCRIPTION_GENDER
    FROM ECOMMERCE.DEV.STG_ECOMMERCE
    
)

SELECT DISTINCT 
GENDER_ID,
DESCRIPTION_GENDER
FROM
DIM_GENDER


-- Derive DIM_IMPORTANCE

WITH DIM_IMPORTANCE AS(

SELECT 
    PRODUCT_IMPORTANCE AS PRODUCT_IMPORTANCE_ID
    FROM ECOMMERCE.DEV.STG_ECOMMERCE
    
)

SELECT DISTINCT 
PRODUCT_IMPORTANCE_ID
FROM
DIM_IMPORTANCE



-- Derive FACT_ECOMMERCE ( Full Update )

WITH FACT_ECOMMERCE AS(

SELECT 
    WAREHOUSE_BLOCK AS WAREHOUSE_BLOCK_ID,
    MODE_OF_SHIPMENT AS MODE_OF_SHIPMENT_ID,
    CUSTOMER_CARE_CALLS,
    CUSTOMER_RATING,
    CAST ( COST_PRODUCT AS DOUBLE ) AS COST_PRODUCT,
    PRIOR_PURCHASES,
    PRODUCT_IMPORTANCE AS PRODUCT_IMPORTANCE_ID,
    GENDER AS GENDER_ID,
    DISCOUNT_OFFERED,811881
    
    WEIGHT_IN_GMS,
    ROUND ( DIV0 ( WEIGHT_IN_GMS , 1000 ),1 ) WEIGHT_IN_KGS
    FROM ECOMMERCE.DEV.STG_ECOMMERCE
    
)

SELECT 
*
FROM
FACT_ECOMMERCE

-- Singular Tests

SELECT * FROM FACT_ECOMMERCE
WHERE DISCOUNT_OFFERED >= 100

