-- Derive DIM Mode Of Shipment

WITH DIM_MODE_SHIPMENT AS(

SELECT 
    MODE_OF_SHIPMENT AS MODE_OF_SHIPMENT_ID,
    CASE WHEN MODE_OF_SHIPMENT = 'Flight' THEN 'Azul'
    WHEN MODE_OF_SHIPMENT = 'Ship' THEN 'Titanic'
    WHEN MODE_OF_SHIPMENT = 'Road' THEN 'Optimus Prime'
    ELSE 'N/A' END AS IN_CHARGE_OF
    FROM {{ ref('stg_ecommerce') }}
    
)

SELECT DISTINCT 
MODE_OF_SHIPMENT_ID,
IN_CHARGE_OF
FROM DIM_MODE_SHIPMENT